git:
  paging:
    colorArg: always
    pager: delta --paging=never

gui:
  # If true, increase the height of the focused side window; creating an accordion effect.
  expandFocusedSidePanel: true

  nerdFontsVersion: "3"

  # How things are filtered when typing '/'.
  # One of 'substring' (default) | 'fuzzy'
  filterMode: fuzzy

  theme:
    activeBorderColor:
      - "#89b4fa"
      - bold
    inactiveBorderColor:
      - "#a6adc8"
    optionsTextColor:
      - "#89b4fa"
    selectedLineBgColor:
      - "#313244"
    cherryPickedCommitBgColor:
      - "#45475a"
    cherryPickedCommitFgColor:
      - "#89b4fa"
    unstagedChangesColor:
      - "#f38ba8"
    defaultFgColor:
      - "#cdd6f4"
    searchingActiveBorderColor:
      - "#f9e2af"

  authorColors:
    "*": "#b4befe"

  spinner:
    # The frames of the spinner animation.
    frames:
      - "⣷"
      - "⣯"
      - "⣟"
      - "⡿"
      - "⢿"
      - "⣻"
      - "⣽"
      - "⣾"

    # The "speed" of the spinner in milliseconds.
    rate: 100

# What to do when opening Lazygit outside of a git repo.
# - 'prompt': (default) ask whether to initialize a new repo or open in the most recent repo
# - 'create': initialize a new repo
# - 'skip': open most recent repo
# - 'quit': exit Lazygit
notARepository: quit

# If true, display a confirmation when subprocess terminates. This allows you to view the output of the subprocess before returning to Lazygit.
promptToReturnFromSubprocess: false
