[".config/zsh/plugins/zsh-nvm.plugin.zsh"]
  type = "file"
  url = "https://raw.githubusercontent.com/lukechilds/zsh-nvm/master/zsh-nvm.plugin.zsh"
  refreshPeriod = "168h"

[".config/zsh/plugins/fast-syntax-highlighting"]
  type = "archive"
  url = "https://github.com/zdharma-continuum/fast-syntax-highlighting/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
